name: Build Kasir Pro APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          echo "GOOGLE_WEB_CLIENT_ID=357452625370-c0c7mqnmhodoebtq4e3323ocfsp3ituo.apps.googleusercontent.com" > .env
          cp .env .env.example
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - run: cat debug.keystore.base64 | base64 --decode > debug.keystore
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleDebug
      - run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/kasir-pro.apk
      - uses: actions/upload-artifact@v4
        with:
          name: Kasir-Pro
          path: app/build/outputs/apk/debug/kasir-pro.apk
